"""All ORM models.

Imported as one module so ``Base.metadata`` is complete before Alembic
autogenerate or ``create_all`` runs.
"""

from database.base import Base
from database.models.approvals import (
    AlertDeduplication,
    Approval,
    BackgroundTask,
    BackgroundTaskEvent,
    Notification,
    NotificationDeliveryAttempt,
    PendingAction,
    PendingReachyNotification,
)
from database.models.core import (
    ActionAuditLog,
    Contact,
    ContactAlias,
    IdempotencyKey,
    IntegrationHealth,
    OwnerProfile,
    ServiceHeartbeat,
    UserPreference,
)
from database.models.scheduling import Reminder, ScheduledJob, Task, TaskRecurrence
from database.models.vision import (
    CameraCalibration,
    CameraSource,
    EvaluationDataset,
    EvaluationResult,
    EvaluationSample,
    EvidenceAsset,
    ModelRun,
    ModelVersion,
    ObjectDetection,
    ObjectEntity,
    ObjectEntityObservation,
    ObjectIdentityRevision,
    ObjectTrack,
    ObservationRequest,
    SceneSnapshot,
    VisualDeletionReceipt,
    VisualEmbedding,
    VisualEvent,
    VisualObservation,
    VisualSpatialRelation,
    VisualWatch,
    VisualZone,
)
from database.models.wardrobe import (
    Outfit,
    OutfitHistory,
    OutfitItem,
    SocialPostHistory,
    WardrobeAvailabilityEvent,
    WardrobeImage,
    WardrobeItem,
)
from database.models.work import (
    BriefingPreference,
    DocumentRecord,
    DocumentSource,
    RegisteredScript,
    ScriptRun,
)

__all__ = [
    "ActionAuditLog",
    "AlertDeduplication",
    "Approval",
    "BackgroundTask",
    "BackgroundTaskEvent",
    "Base",
    "BriefingPreference",
    "CameraCalibration",
    "CameraSource",
    "Contact",
    "ContactAlias",
    "DocumentRecord",
    "DocumentSource",
    "EvaluationDataset",
    "EvaluationResult",
    "EvaluationSample",
    "EvidenceAsset",
    "IdempotencyKey",
    "IntegrationHealth",
    "ModelRun",
    "ModelVersion",
    "Notification",
    "NotificationDeliveryAttempt",
    "ObjectDetection",
    "ObjectEntity",
    "ObjectEntityObservation",
    "ObjectIdentityRevision",
    "ObjectTrack",
    "ObservationRequest",
    "Outfit",
    "OutfitHistory",
    "OutfitItem",
    "OwnerProfile",
    "PendingAction",
    "PendingReachyNotification",
    "RegisteredScript",
    "Reminder",
    "SceneSnapshot",
    "ScheduledJob",
    "ScriptRun",
    "ServiceHeartbeat",
    "SocialPostHistory",
    "Task",
    "TaskRecurrence",
    "UserPreference",
    "VisualDeletionReceipt",
    "VisualEmbedding",
    "VisualEvent",
    "VisualObservation",
    "VisualSpatialRelation",
    "VisualWatch",
    "VisualZone",
    "WardrobeAvailabilityEvent",
    "WardrobeImage",
    "WardrobeItem",
]
