"""visual spatial memory schema

Revision ID: 74434d688fb6
Revises: ce581db514e8
Create Date: 2026-09-02 22:19:28.921841
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '74434d688fb6'
down_revision: str | None = 'ce581db514e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_sources',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('device_label', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_sources')),
    sa.UniqueConstraint('name', name='uq_camera_sources_name')
    )
    with op.batch_alter_table('camera_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_sources_created_at'), ['created_at'], unique=False)

    op.create_table('evaluation_datasets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('frame_index_sha256', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['evaluation_datasets.id'], name=op.f('fk_evaluation_datasets_parent_id_evaluation_datasets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_datasets')),
    sa.UniqueConstraint('name', 'version', name='uq_evaluation_datasets_name_version')
    )
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_datasets_created_at'), ['created_at'], unique=False)

    op.create_table('model_versions',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('task', sa.String(length=40), nullable=False),
    sa.Column('weights_sha256', sa.String(length=64), nullable=True),
    sa.Column('licence', sa.String(length=80), nullable=True),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('name', 'version', name='uq_model_versions_name_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_created_at'), ['created_at'], unique=False)

    op.create_table('object_identity_revisions',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('from_entity_id', sa.String(length=36), nullable=False),
    sa.Column('to_entity_id', sa.String(length=36), nullable=False),
    sa.Column('moved_detection_ids', sa.Text(), nullable=False, comment='JSON array'),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_identity_revisions'))
    )
    with op.batch_alter_table('object_identity_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_object_identity_revisions_kind_occurred_at', ['kind', 'occurred_at'], unique=False)

    op.create_table('visual_deletion_receipts',
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('counts_json', sa.Text(), nullable=False, comment='JSON object'),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('verified_empty', sa.Boolean(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_deletion_receipts'))
    )
    with op.batch_alter_table('visual_deletion_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_visual_deletion_receipts_requested_at', ['requested_at'], unique=False)

    op.create_table('visual_embeddings',
    sa.Column('owner_kind', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('space', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.String(length=20), nullable=False),
    sa.Column('vector_sha256', sa.String(length=64), nullable=False),
    sa.Column('sidecar_key', sa.String(length=200), nullable=True),
    sa.Column('is_person', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_embeddings')),
    sa.UniqueConstraint('owner_kind', 'owner_id', 'space', 'model_name', 'model_version', name='uq_visual_embeddings_owner_space_model')
    )
    with op.batch_alter_table('visual_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_embeddings_created_at'), ['created_at'], unique=False)

    op.create_table('visual_zones',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalised_name', sa.String(length=200), nullable=False),
    sa.Column('privacy_sensitive', sa.Boolean(), nullable=False),
    sa.Column('capture_allowed', sa.Boolean(), nullable=False),
    sa.Column('churn_class', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_zones')),
    sa.UniqueConstraint('normalised_name', name='uq_visual_zones_normalised_name')
    )
    with op.batch_alter_table('visual_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_zones_created_at'), ['created_at'], unique=False)

    op.create_table('camera_calibrations',
    sa.Column('camera_source_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('distortion_model', sa.String(length=32), nullable=False),
    sa.Column('intrinsics_k', sa.Text(), nullable=True, comment='JSON 3x3 matrix, row-major'),
    sa.Column('intrinsics_d', sa.Text(), nullable=True, comment='JSON distortion coefficients'),
    sa.Column('intrinsics_status', sa.String(length=20), nullable=False),
    sa.Column('t_head_cam', sa.Text(), nullable=True, comment='JSON 4x4 nominal head-from-camera transform'),
    sa.Column('t_head_cam_status', sa.String(length=20), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('reprojection_rms', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_source_id'], ['camera_sources.id'], name=op.f('fk_camera_calibrations_camera_source_id_camera_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_calibrations')),
    sa.UniqueConstraint('version', name='uq_camera_calibrations_version')
    )
    with op.batch_alter_table('camera_calibrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_calibrations_camera_source_id'), ['camera_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_calibrations_created_at'), ['created_at'], unique=False)

    op.create_table('evidence_assets',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('relative_path', sa.String(length=400), nullable=False),
    sa.Column('dhash64', sa.String(length=16), nullable=True),
    sa.Column('phash64', sa.String(length=16), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=40), nullable=False),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('contains_person', sa.Boolean(), nullable=False),
    sa.Column('privacy_sensitive', sa.Boolean(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False, comment='Hint only; recompute from FKs each sweep'),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('pose_bucket', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['visual_zones.id'], name=op.f('fk_evidence_assets_zone_id_visual_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_assets')),
    sa.UniqueConstraint('content_hash', name='uq_evidence_assets_content_hash'),
    sa.UniqueConstraint('idempotency_key', name='uq_evidence_assets_idempotency_key')
    )
    with op.batch_alter_table('evidence_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_evidence_assets_dhash64', ['dhash64'], unique=False)
        batch_op.create_index('ix_evidence_assets_phash64', ['phash64'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_assets_pose_bucket'), ['pose_bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_assets_retention_class'), ['retention_class'], unique=False)
        batch_op.create_index('ix_evidence_assets_state_expires_at', ['state', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_assets_zone_id'), ['zone_id'], unique=False)

    op.create_table('model_runs',
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(length=40), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True, comment='JSON object'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_model_runs_model_version_id_model_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_model_runs_version_started_at', ['model_version_id', 'started_at'], unique=False)

    op.create_table('observation_requests',
    sa.Column('camera_source_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('preset_id', sa.String(length=80), nullable=True),
    sa.Column('query_text', sa.String(length=500), nullable=True),
    sa.Column('reject_reason', sa.String(length=80), nullable=True),
    sa.Column('abort_reason', sa.String(length=80), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True, comment='JSON object'),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_source_id'], ['camera_sources.id'], name=op.f('fk_observation_requests_camera_source_id_camera_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['visual_zones.id'], name=op.f('fk_observation_requests_zone_id_visual_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_requests')),
    sa.UniqueConstraint('idempotency_key', name='uq_observation_requests_idempotency_key')
    )
    with op.batch_alter_table('observation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_requests_camera_source_id'), ['camera_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_requests_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_requests_zone_id'), ['zone_id'], unique=False)

    op.create_table('evaluation_samples',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('suite', sa.String(length=80), nullable=False),
    sa.Column('external_key', sa.String(length=200), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('split', sa.String(length=20), nullable=False),
    sa.Column('ground_truth_json', sa.Text(), nullable=False, comment='JSON object'),
    sa.Column('annotation_version', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], name=op.f('fk_evaluation_samples_dataset_id_evaluation_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_assets.id'], name=op.f('fk_evaluation_samples_evidence_id_evidence_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_samples')),
    sa.UniqueConstraint('suite', 'external_key', name='uq_evaluation_samples_suite_external_key')
    )
    with op.batch_alter_table('evaluation_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_samples_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_samples_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('object_entities',
    sa.Column('display_label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_person', sa.Boolean(), nullable=False, comment='Must stay false; person entities are unrepresentable'),
    sa.Column('blocks_embeddings', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('last_seen_observation_id', sa.String(length=36), nullable=True),
    sa.Column('canonical_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('prototype_embedding', sa.Text(), nullable=True, comment='JSON float32 prototype; empty for persons'),
    sa.Column('prototype_vector_sha256', sa.String(length=64), nullable=True),
    sa.Column('merged_into_id', sa.String(length=36), nullable=True),
    sa.Column('belief', sa.Float(), nullable=True),
    sa.Column('need_look', sa.Float(), nullable=True),
    sa.Column('need_look_terms', sa.Text(), nullable=True, comment='JSON object'),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('contradiction_count', sa.Integer(), nullable=False),
    sa.Column('last_confirmed_utc', sa.DateTime(), nullable=True),
    sa.Column('churn_class', sa.String(length=20), nullable=False),
    sa.Column('staleness_half_life_s', sa.Integer(), nullable=True),
    sa.Column('scan_completeness', sa.Float(), nullable=True),
    sa.Column('evidence_frame_ids', sa.Text(), nullable=True, comment='JSON array of observation ids'),
    sa.Column('provenance_state', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_evidence_id'], ['evidence_assets.id'], name=op.f('fk_object_entities_canonical_evidence_id_evidence_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['object_entities.id'], name=op.f('fk_object_entities_merged_into_id_object_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['visual_zones.id'], name=op.f('fk_object_entities_zone_id_visual_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_entities'))
    )
    with op.batch_alter_table('object_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_entities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_entities_merged_into_id'), ['merged_into_id'], unique=False)
        batch_op.create_index('ix_object_entities_status_last_seen_at', ['status', 'last_seen_at'], unique=False)
        batch_op.create_index('ix_object_entities_zone_last_seen_at', ['zone_id', 'last_seen_at'], unique=False)

    op.create_table('scene_snapshots',
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('abort_reason', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('coverage_json', sa.Text(), nullable=True, comment='JSON object'),
    sa.Column('viewpoint_count', sa.Integer(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['observation_requests.id'], name=op.f('fk_scene_snapshots_request_id_observation_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['visual_zones.id'], name=op.f('fk_scene_snapshots_zone_id_visual_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_snapshots')),
    sa.UniqueConstraint('idempotency_key', name='uq_scene_snapshots_idempotency_key')
    )
    with op.batch_alter_table('scene_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_scene_snapshots_kind_started_at', ['kind', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_snapshots_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_snapshots_zone_id'), ['zone_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('model_run_id', sa.String(length=36), nullable=True),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True, comment='JSON object'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], name=op.f('fk_evaluation_results_dataset_id_evaluation_datasets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_evaluation_results_model_version_id_model_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_id'], ['evaluation_samples.id'], name=op.f('fk_evaluation_results_sample_id_evaluation_samples'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_results')),
    sa.UniqueConstraint('idempotency_key', name='uq_evaluation_results_idempotency_key')
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_evaluation_results_dataset_created_at', ['dataset_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_results_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_results_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_results_sample_id'), ['sample_id'], unique=False)

    op.create_table('object_tracks',
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['scene_snapshots.id'], name=op.f('fk_object_tracks_snapshot_id_scene_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_tracks'))
    )
    with op.batch_alter_table('object_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_tracks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_tracks_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index('ix_object_tracks_state_last_seen_at', ['state', 'last_seen_at'], unique=False)

    op.create_table('visual_observations',
    sa.Column('camera_source_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('calibration_id', sa.String(length=36), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('captured_at_pi', sa.DateTime(), nullable=True),
    sa.Column('captured_at_pc', sa.DateTime(), nullable=True),
    sa.Column('clock_offset_ns', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('calibration_version', sa.String(length=80), nullable=True),
    sa.Column('intrinsics_k', sa.Text(), nullable=True, comment='JSON 3x3, valid at recorded resolution'),
    sa.Column('intrinsics_d', sa.Text(), nullable=True, comment='JSON distortion coefficients'),
    sa.Column('distortion_model', sa.String(length=32), nullable=False),
    sa.Column('intrinsics_status', sa.String(length=20), nullable=False),
    sa.Column('t_head_cam', sa.Text(), nullable=True, comment='JSON 4x4, nominal, SDK-version-dependent'),
    sa.Column('head_pose_4x4', sa.Text(), nullable=True, comment='JSON 4x4 derived pose'),
    sa.Column('head_joints_rad', sa.Text(), nullable=True, comment='JSON array of 7 measured radians'),
    sa.Column('body_yaw_rad', sa.Float(), nullable=True),
    sa.Column('body_yaw_source', sa.String(length=20), nullable=False),
    sa.Column('automatic_body_yaw', sa.Boolean(), nullable=False),
    sa.Column('head_pose_is_settled', sa.Boolean(), nullable=False),
    sa.Column('joint_velocity_max_rad_s', sa.Float(), nullable=True),
    sa.Column('pose_capture_skew_ns', sa.Integer(), nullable=True),
    sa.Column('pose_status', sa.String(length=20), nullable=False),
    sa.Column('viewpoint_label', sa.String(length=80), nullable=True),
    sa.Column('pose_bucket', sa.String(length=80), nullable=True),
    sa.Column('world_frame_status', sa.String(length=20), nullable=False),
    sa.Column('depth_model', sa.String(length=80), nullable=True),
    sa.Column('depth_model_version', sa.String(length=80), nullable=True),
    sa.Column('depth_model_licence', sa.String(length=80), nullable=True),
    sa.Column('depth_space', sa.String(length=32), nullable=False),
    sa.Column('depth_output_kind', sa.String(length=32), nullable=True),
    sa.Column('depth_input_space', sa.String(length=40), nullable=True),
    sa.Column('depth_normalisation', sa.String(length=40), nullable=True),
    sa.Column('depth_norm_lo', sa.Float(), nullable=True),
    sa.Column('depth_norm_hi', sa.Float(), nullable=True),
    sa.Column('sky_fraction', sa.Float(), nullable=True),
    sa.Column('depth_status', sa.String(length=20), nullable=False),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('blur_flag', sa.Boolean(), nullable=False),
    sa.Column('exposure_flag', sa.Boolean(), nullable=False),
    sa.Column('saturated_fraction', sa.Float(), nullable=True),
    sa.Column('low_texture', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_flags', sa.Text(), nullable=True, comment='JSON array'),
    sa.Column('mean_luma', sa.Float(), nullable=True),
    sa.Column('laplacian_variance', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('dhash64', sa.String(length=16), nullable=True),
    sa.Column('phash64', sa.String(length=16), nullable=True),
    sa.Column('region_observed', sa.Boolean(), nullable=False),
    sa.Column('camera_health_json', sa.Text(), nullable=True, comment='JSON object'),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('model_run_id', sa.String(length=36), nullable=True),
    sa.Column('full_frame_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('thumbnail_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calibration_id'], ['camera_calibrations.id'], name=op.f('fk_visual_observations_calibration_id_camera_calibrations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_source_id'], ['camera_sources.id'], name=op.f('fk_visual_observations_camera_source_id_camera_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['full_frame_evidence_id'], ['evidence_assets.id'], name=op.f('fk_visual_observations_full_frame_evidence_id_evidence_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['observation_requests.id'], name=op.f('fk_visual_observations_request_id_observation_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['scene_snapshots.id'], name=op.f('fk_visual_observations_snapshot_id_scene_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thumbnail_evidence_id'], ['evidence_assets.id'], name=op.f('fk_visual_observations_thumbnail_evidence_id_evidence_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['visual_zones.id'], name=op.f('fk_visual_observations_zone_id_visual_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_observations')),
    sa.UniqueConstraint('idempotency_key', name='uq_visual_observations_idempotency_key')
    )
    with op.batch_alter_table('visual_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_observations_calibration_id'), ['calibration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_observations_camera_source_id'), ['camera_source_id'], unique=False)
        batch_op.create_index('ix_visual_observations_captured_at', ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_observations_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_observations_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_observations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_observations_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_observations_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index('ix_visual_observations_trigger_captured_at', ['trigger', 'captured_at'], unique=False)
        batch_op.create_index('ix_visual_observations_zone_captured_at', ['zone_id', 'captured_at'], unique=False)

    op.create_table('visual_watches',
    sa.Column('query_json', sa.Text(), nullable=False, comment='JSON object'),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('next_check_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_json', sa.Text(), nullable=True, comment='JSON object'),
    sa.Column('baseline_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_evidence_id'], ['evidence_assets.id'], name=op.f('fk_visual_watches_baseline_evidence_id_evidence_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['object_entities.id'], name=op.f('fk_visual_watches_entity_id_object_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['visual_zones.id'], name=op.f('fk_visual_watches_zone_id_visual_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_watches')),
    sa.UniqueConstraint('idempotency_key', name='uq_visual_watches_idempotency_key')
    )
    with op.batch_alter_table('visual_watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_watches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_watches_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index('ix_visual_watches_status_next_check_at', ['status', 'next_check_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_watches_zone_id'), ['zone_id'], unique=False)

    op.create_table('object_detections',
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('label_status', sa.String(length=20), nullable=False),
    sa.Column('is_person', sa.Boolean(), nullable=False),
    sa.Column('blocks_entity', sa.Boolean(), nullable=False),
    sa.Column('blocks_embedding', sa.Boolean(), nullable=False),
    sa.Column('bbox_x0', sa.Float(), nullable=True),
    sa.Column('bbox_y0', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('mask_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('crop_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('camera_ray_unit', sa.Text(), nullable=True, comment='JSON unit vector in camera frame'),
    sa.Column('camera_ray_status', sa.String(length=20), nullable=False),
    sa.Column('camera_ray_body', sa.Text(), nullable=True, comment='JSON unit vector derived into body frame'),
    sa.Column('camera_ray_cone_deg', sa.Float(), nullable=True),
    sa.Column('depth_median', sa.Float(), nullable=True),
    sa.Column('depth_p10', sa.Float(), nullable=True),
    sa.Column('depth_p25', sa.Float(), nullable=True),
    sa.Column('depth_p75', sa.Float(), nullable=True),
    sa.Column('depth_p90', sa.Float(), nullable=True),
    sa.Column('depth_iqr', sa.Float(), nullable=True),
    sa.Column('depth_bottom_edge_median', sa.Float(), nullable=True),
    sa.Column('depth_conf_median', sa.Float(), nullable=True),
    sa.Column('depth_flicker_std', sa.Float(), nullable=True),
    sa.Column('depth_valid_fraction', sa.Float(), nullable=True),
    sa.Column('mask_touches_border', sa.Boolean(), nullable=False),
    sa.Column('mask_border_fraction', sa.Float(), nullable=True),
    sa.Column('mask_radial_norm', sa.Float(), nullable=True),
    sa.Column('mask_area_px', sa.Integer(), nullable=True),
    sa.Column('mask_area_fraction', sa.Float(), nullable=True),
    sa.Column('mask_thinness', sa.Float(), nullable=True),
    sa.Column('occlusion_ratio', sa.Float(), nullable=True),
    sa.Column('detection_score_raw', sa.Float(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_calibration_version', sa.String(length=80), nullable=True),
    sa.Column('association_margin', sa.Float(), nullable=True),
    sa.Column('n_competing_candidates', sa.Integer(), nullable=True),
    sa.Column('n_similar_instances', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('provenance_state', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('model_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_evidence_id'], ['evidence_assets.id'], name=op.f('fk_object_detections_crop_evidence_id_evidence_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['object_entities.id'], name=op.f('fk_object_detections_entity_id_object_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mask_evidence_id'], ['evidence_assets.id'], name=op.f('fk_object_detections_mask_evidence_id_evidence_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['observation_id'], ['visual_observations.id'], name=op.f('fk_object_detections_observation_id_visual_observations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['object_tracks.id'], name=op.f('fk_object_detections_track_id_object_tracks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_detections'))
    )
    with op.batch_alter_table('object_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_detections_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_object_detections_entity_captured_at', ['entity_id', 'captured_at'], unique=False)
        batch_op.create_index('ix_object_detections_label_captured_at', ['label', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_detections_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_detections_track_id'), ['track_id'], unique=False)

    op.create_table('visual_events',
    sa.Column('occurred_after', sa.DateTime(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('watch_id', sa.String(length=36), nullable=True),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('before_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('after_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True, comment='JSON object'),
    sa.Column('dedup_key', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['after_evidence_id'], ['evidence_assets.id'], name=op.f('fk_visual_events_after_evidence_id_evidence_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['before_evidence_id'], ['evidence_assets.id'], name=op.f('fk_visual_events_before_evidence_id_evidence_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['object_entities.id'], name=op.f('fk_visual_events_entity_id_object_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['observation_id'], ['visual_observations.id'], name=op.f('fk_visual_events_observation_id_visual_observations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['watch_id'], ['visual_watches.id'], name=op.f('fk_visual_events_watch_id_visual_watches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['visual_zones.id'], name=op.f('fk_visual_events_zone_id_visual_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_events')),
    sa.UniqueConstraint('dedup_key', name='uq_visual_events_dedup_key'),
    sa.UniqueConstraint('idempotency_key', name='uq_visual_events_idempotency_key')
    )
    with op.batch_alter_table('visual_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index('ix_visual_events_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_visual_events_type_occurred_at', ['event_type', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_events_watch_id'), ['watch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_events_zone_id'), ['zone_id'], unique=False)

    op.create_table('object_entity_observations',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('detection_id', sa.String(length=36), nullable=True),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['object_detections.id'], name=op.f('fk_object_entity_observations_detection_id_object_detections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['object_entities.id'], name=op.f('fk_object_entity_observations_entity_id_object_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['visual_observations.id'], name=op.f('fk_object_entity_observations_observation_id_visual_observations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_entity_observations'))
    )
    with op.batch_alter_table('object_entity_observations', schema=None) as batch_op:
        batch_op.create_index('ix_object_entity_observations_entity_observed_at', ['entity_id', 'observed_at'], unique=False)

    op.create_table('visual_spatial_relations',
    sa.Column('predicate', sa.String(length=32), nullable=False),
    sa.Column('frame_class', sa.String(length=20), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=36), nullable=True),
    sa.Column('object_entity_id', sa.String(length=36), nullable=True),
    sa.Column('subject_detection_id', sa.String(length=36), nullable=True),
    sa.Column('object_detection_id', sa.String(length=36), nullable=True),
    sa.Column('observed_from_observation_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_cap', sa.Float(), nullable=True),
    sa.Column('needs_reobservation', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('provenance_status', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('model_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['object_detection_id'], ['object_detections.id'], name=op.f('fk_visual_spatial_relations_object_detection_id_object_detections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_entity_id'], ['object_entities.id'], name=op.f('fk_visual_spatial_relations_object_entity_id_object_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['observed_from_observation_id'], ['visual_observations.id'], name=op.f('fk_visual_spatial_relations_observed_from_observation_id_visual_observations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_detection_id'], ['object_detections.id'], name=op.f('fk_visual_spatial_relations_subject_detection_id_object_detections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['object_entities.id'], name=op.f('fk_visual_spatial_relations_subject_entity_id_object_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['visual_zones.id'], name=op.f('fk_visual_spatial_relations_zone_id_visual_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_spatial_relations'))
    )
    with op.batch_alter_table('visual_spatial_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_spatial_relations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_spatial_relations_object_entity_id'), ['object_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_spatial_relations_observed_from_observation_id'), ['observed_from_observation_id'], unique=False)
        batch_op.create_index('ix_visual_spatial_relations_predicate_captured_at', ['predicate', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_spatial_relations_subject_entity_id'), ['subject_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visual_spatial_relations_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visual_spatial_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_spatial_relations_zone_id'))
        batch_op.drop_index(batch_op.f('ix_visual_spatial_relations_subject_entity_id'))
        batch_op.drop_index('ix_visual_spatial_relations_predicate_captured_at')
        batch_op.drop_index(batch_op.f('ix_visual_spatial_relations_observed_from_observation_id'))
        batch_op.drop_index(batch_op.f('ix_visual_spatial_relations_object_entity_id'))
        batch_op.drop_index(batch_op.f('ix_visual_spatial_relations_created_at'))

    op.drop_table('visual_spatial_relations')
    with op.batch_alter_table('object_entity_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_object_entity_observations_entity_observed_at')

    op.drop_table('object_entity_observations')
    with op.batch_alter_table('visual_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_events_zone_id'))
        batch_op.drop_index(batch_op.f('ix_visual_events_watch_id'))
        batch_op.drop_index('ix_visual_events_type_occurred_at')
        batch_op.drop_index('ix_visual_events_occurred_at')
        batch_op.drop_index(batch_op.f('ix_visual_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_visual_events_correlation_id'))

    op.drop_table('visual_events')
    with op.batch_alter_table('object_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_detections_track_id'))
        batch_op.drop_index(batch_op.f('ix_object_detections_observation_id'))
        batch_op.drop_index('ix_object_detections_label_captured_at')
        batch_op.drop_index('ix_object_detections_entity_captured_at')
        batch_op.drop_index(batch_op.f('ix_object_detections_created_at'))

    op.drop_table('object_detections')
    with op.batch_alter_table('visual_watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_watches_zone_id'))
        batch_op.drop_index('ix_visual_watches_status_next_check_at')
        batch_op.drop_index(batch_op.f('ix_visual_watches_entity_id'))
        batch_op.drop_index(batch_op.f('ix_visual_watches_created_at'))

    op.drop_table('visual_watches')
    with op.batch_alter_table('visual_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_visual_observations_zone_captured_at')
        batch_op.drop_index('ix_visual_observations_trigger_captured_at')
        batch_op.drop_index(batch_op.f('ix_visual_observations_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_visual_observations_request_id'))
        batch_op.drop_index(batch_op.f('ix_visual_observations_created_at'))
        batch_op.drop_index(batch_op.f('ix_visual_observations_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_visual_observations_content_hash'))
        batch_op.drop_index('ix_visual_observations_captured_at')
        batch_op.drop_index(batch_op.f('ix_visual_observations_camera_source_id'))
        batch_op.drop_index(batch_op.f('ix_visual_observations_calibration_id'))

    op.drop_table('visual_observations')
    with op.batch_alter_table('object_tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_object_tracks_state_last_seen_at')
        batch_op.drop_index(batch_op.f('ix_object_tracks_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_object_tracks_created_at'))

    op.drop_table('object_tracks')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_sample_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_results_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_results_dataset_id'))
        batch_op.drop_index('ix_evaluation_results_dataset_created_at')
        batch_op.drop_index(batch_op.f('ix_evaluation_results_created_at'))

    op.drop_table('evaluation_results')
    with op.batch_alter_table('scene_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_snapshots_zone_id'))
        batch_op.drop_index(batch_op.f('ix_scene_snapshots_request_id'))
        batch_op.drop_index('ix_scene_snapshots_kind_started_at')
        batch_op.drop_index(batch_op.f('ix_scene_snapshots_created_at'))

    op.drop_table('scene_snapshots')
    with op.batch_alter_table('object_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_object_entities_zone_last_seen_at')
        batch_op.drop_index('ix_object_entities_status_last_seen_at')
        batch_op.drop_index(batch_op.f('ix_object_entities_merged_into_id'))
        batch_op.drop_index(batch_op.f('ix_object_entities_created_at'))

    op.drop_table('object_entities')
    with op.batch_alter_table('evaluation_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_samples_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_samples_created_at'))

    op.drop_table('evaluation_samples')
    with op.batch_alter_table('observation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_requests_zone_id'))
        batch_op.drop_index(batch_op.f('ix_observation_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_observation_requests_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_observation_requests_camera_source_id'))

    op.drop_table('observation_requests')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_model_runs_version_started_at')
        batch_op.drop_index(batch_op.f('ix_model_runs_created_at'))

    op.drop_table('model_runs')
    with op.batch_alter_table('evidence_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_assets_zone_id'))
        batch_op.drop_index('ix_evidence_assets_state_expires_at')
        batch_op.drop_index(batch_op.f('ix_evidence_assets_retention_class'))
        batch_op.drop_index(batch_op.f('ix_evidence_assets_pose_bucket'))
        batch_op.drop_index('ix_evidence_assets_phash64')
        batch_op.drop_index('ix_evidence_assets_dhash64')
        batch_op.drop_index(batch_op.f('ix_evidence_assets_created_at'))

    op.drop_table('evidence_assets')
    with op.batch_alter_table('camera_calibrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_calibrations_created_at'))
        batch_op.drop_index(batch_op.f('ix_camera_calibrations_camera_source_id'))

    op.drop_table('camera_calibrations')
    with op.batch_alter_table('visual_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_zones_created_at'))

    op.drop_table('visual_zones')
    with op.batch_alter_table('visual_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_embeddings_created_at'))

    op.drop_table('visual_embeddings')
    with op.batch_alter_table('visual_deletion_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_visual_deletion_receipts_requested_at')

    op.drop_table('visual_deletion_receipts')
    with op.batch_alter_table('object_identity_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_object_identity_revisions_kind_occurred_at')

    op.drop_table('object_identity_revisions')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_created_at'))

    op.drop_table('model_versions')
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_datasets_created_at'))

    op.drop_table('evaluation_datasets')
    with op.batch_alter_table('camera_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_sources_created_at'))

    op.drop_table('camera_sources')
    # ### end Alembic commands ###
