"""initial schema

Revision ID: ce581db514e8
Revises: 
Create Date: 2026-08-02 18:28:08.707919
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ce581db514e8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_audit_log',
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('payload_preview', sa.Text(), nullable=True, comment='Redacted canonical payload, truncated'),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_audit_log'))
    )
    with op.batch_alter_table('action_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_audit_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_audit_log_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_audit_log_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_audit_log_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('alert_deduplications',
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('alert_kind', sa.String(length=60), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('notify_count', sa.Integer(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_deduplications')),
    sa.UniqueConstraint('dedup_key', name='uq_alert_deduplications_dedup_key')
    )
    with op.batch_alter_table('alert_deduplications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_deduplications_alert_kind'), ['alert_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_deduplications_created_at'), ['created_at'], unique=False)

    op.create_table('background_tasks',
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('result_path', sa.Text(), nullable=True, comment='Large results live under APP_DATA_DIR/task_outputs'),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_tasks')),
    sa.UniqueConstraint('idempotency_key', name='uq_background_tasks_idempotency_key')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_lease_owner'), ['lease_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_status'), ['status'], unique=False)
        batch_op.create_index('ix_background_tasks_status_available_at', ['status', 'available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('contacts',
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('normalised_name', sa.String(length=200), nullable=False),
    sa.Column('primary_email', sa.String(length=320), nullable=True),
    sa.Column('secondary_emails', sa.Text(), nullable=True, comment='JSON array'),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('relationship_tag', sa.String(length=60), nullable=True),
    sa.Column('organisation', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_external_id'), ['external_id'], unique=False)
        batch_op.create_index('ix_contacts_normalised_name', ['normalised_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_primary_email'), ['primary_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_relationship_tag'), ['relationship_tag'], unique=False)

    op.create_table('document_sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('root_path', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('follow_symlinks', sa.Boolean(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('last_index_duration_ms', sa.Integer(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sources')),
    sa.UniqueConstraint('root_path', name='uq_document_sources_root_path')
    )
    with op.batch_alter_table('document_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sources_created_at'), ['created_at'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_keys_scope_key')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_idempotency_keys_expires_at', ['expires_at'], unique=False)

    op.create_table('integration_health',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_health')),
    sa.UniqueConstraint('name', name='uq_integration_health_name')
    )
    with op.batch_alter_table('integration_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_health_created_at'), ['created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=True),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('attachment_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_created_at_severity', ['created_at', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    op.create_table('outfits',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('occasion', sa.String(length=60), nullable=True),
    sa.Column('seasons', sa.Text(), nullable=False),
    sa.Column('formality', sa.Integer(), nullable=False),
    sa.Column('min_temperature_c', sa.Float(), nullable=True),
    sa.Column('max_temperature_c', sa.Float(), nullable=True),
    sa.Column('weather_conditions', sa.Text(), nullable=True, comment='JSON array'),
    sa.Column('image_path', sa.String(length=400), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('assistant_rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('last_worn_on', sa.Date(), nullable=True),
    sa.Column('last_posted_on', sa.Date(), nullable=True),
    sa.Column('times_worn', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outfits'))
    )
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfits_last_worn_on'), ['last_worn_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfits_occasion'), ['occasion'], unique=False)

    op.create_table('owner_profile',
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owner_profile'))
    )
    with op.batch_alter_table('owner_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_profile_created_at'), ['created_at'], unique=False)

    op.create_table('pending_actions',
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False, comment='Canonical JSON'),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('preview_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_result', sa.Text(), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True, comment='Provider-side id created by the execution'),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('background_task_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_actions')),
    sa.UniqueConstraint('idempotency_key', name='uq_pending_actions_idempotency_key')
    )
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_actions_background_task_id'), ['background_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_actions_payload_hash'), ['payload_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_actions_status'), ['status'], unique=False)
        batch_op.create_index('ix_pending_actions_status_expires_at', ['status', 'expires_at'], unique=False)

    op.create_table('pending_reachy_notifications',
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('spoken_text', sa.Text(), nullable=False, comment='Short phrasing suitable for a voice turn'),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_reachy_notifications'))
    )
    with op.batch_alter_table('pending_reachy_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_pending_reachy_notifications_ack', ['acknowledged', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_reachy_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('registered_scripts',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('executable', sa.String(length=500), nullable=False),
    sa.Column('working_directory', sa.String(length=500), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('load_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registered_scripts')),
    sa.UniqueConstraint('name', name='uq_registered_scripts_name')
    )
    with op.batch_alter_table('registered_scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registered_scripts_created_at'), ['created_at'], unique=False)

    op.create_table('scheduled_jobs',
    sa.Column('job_id', sa.String(length=120), nullable=False),
    sa.Column('job_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_kind', sa.String(length=20), nullable=False),
    sa.Column('trigger_config', sa.Text(), nullable=True, comment='JSON'),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('missed_count', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_jobs')),
    sa.UniqueConstraint('job_id', name='uq_scheduled_jobs_job_id')
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_resource_id'), ['resource_id'], unique=False)

    op.create_table('service_heartbeats',
    sa.Column('service_name', sa.String(length=60), nullable=False),
    sa.Column('instance_id', sa.String(length=80), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_heartbeats')),
    sa.UniqueConstraint('service_name', name='uq_service_heartbeats_service_name')
    )
    with op.batch_alter_table('service_heartbeats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_heartbeats_created_at'), ['created_at'], unique=False)

    op.create_table('task_recurrences',
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('by_weekday', sa.String(length=40), nullable=True, comment='Comma-separated 0-6, Monday=0'),
    sa.Column('by_monthday', sa.Integer(), nullable=True),
    sa.Column('at_hour', sa.Integer(), nullable=False),
    sa.Column('at_minute', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('max_occurrences', sa.Integer(), nullable=True),
    sa.Column('occurrences_fired', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_recurrences'))
    )
    with op.batch_alter_table('task_recurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_recurrences_created_at'), ['created_at'], unique=False)

    op.create_table('wardrobe_items',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subcategory', sa.String(length=60), nullable=True),
    sa.Column('primary_color', sa.String(length=40), nullable=False),
    sa.Column('secondary_colors', sa.Text(), nullable=True, comment='JSON array'),
    sa.Column('pattern', sa.String(length=40), nullable=False),
    sa.Column('material', sa.String(length=60), nullable=True),
    sa.Column('seasons', sa.Text(), nullable=False, comment='JSON array'),
    sa.Column('formality', sa.Integer(), nullable=False, comment='1 loungewear to 5 formal'),
    sa.Column('fit', sa.String(length=40), nullable=True),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('warmth', sa.Integer(), nullable=False, comment='1 very light to 5 very warm'),
    sa.Column('water_resistant', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('laundry_status', sa.String(length=20), nullable=False),
    sa.Column('wears_since_wash', sa.Integer(), nullable=False),
    sa.Column('max_wears_before_wash', sa.Integer(), nullable=False),
    sa.Column('last_worn_on', sa.Date(), nullable=True),
    sa.Column('last_posted_on', sa.Date(), nullable=True),
    sa.Column('times_worn', sa.Integer(), nullable=False),
    sa.Column('favourite_rating', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('embedding_ref', sa.Text(), nullable=True, comment='Optional sidecar path produced by a pluggable embedder'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wardrobe_items'))
    )
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wardrobe_items_category'), ['category'], unique=False)
        batch_op.create_index('ix_wardrobe_items_category_archived', ['category', 'archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_wardrobe_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wardrobe_items_last_worn_on'), ['last_worn_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_wardrobe_items_laundry_status'), ['laundry_status'], unique=False)
        batch_op.create_index('ix_wardrobe_items_primary_color', ['primary_color'], unique=False)

    op.create_table('approvals',
    sa.Column('pending_action_id', sa.String(length=36), nullable=False),
    sa.Column('callback_token', sa.String(length=32), nullable=False, comment='Opaque id carried in the Telegram callback. Not the action id.'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_chat_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('channel_message_id', sa.String(length=60), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pending_action_id'], ['pending_actions.id'], name=op.f('fk_approvals_pending_action_id_pending_actions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('callback_token', name='uq_approvals_callback_token'),
    sa.UniqueConstraint('pending_action_id', name='uq_approvals_pending_action_id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)
        batch_op.create_index('ix_approvals_status_expires_at', ['status', 'expires_at'], unique=False)

    op.create_table('background_task_events',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['background_tasks.id'], name=op.f('fk_background_task_events_task_id_background_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_task_events'))
    )
    with op.batch_alter_table('background_task_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_task_events_task_id'), ['task_id'], unique=False)

    op.create_table('briefing_preferences',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('send_hour', sa.Integer(), nullable=False),
    sa.Column('send_minute', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('sections_json', sa.Text(), nullable=False),
    sa.Column('channels_json', sa.Text(), nullable=False),
    sa.Column('quiet_hours_start', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_end', sa.Integer(), nullable=True),
    sa.Column('urgency_threshold', sa.String(length=20), nullable=False),
    sa.Column('vip_contact_ids_json', sa.Text(), nullable=False),
    sa.Column('commute_start_hour', sa.Integer(), nullable=True),
    sa.Column('commute_end_hour', sa.Integer(), nullable=True),
    sa.Column('include_outfit', sa.Boolean(), nullable=False),
    sa.Column('formatter', sa.String(length=30), nullable=False),
    sa.Column('disk_warning_percent', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner_profile.id'], name=op.f('fk_briefing_preferences_owner_id_owner_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_briefing_preferences')),
    sa.UniqueConstraint('owner_id', name='uq_briefing_preferences_owner_id')
    )
    with op.batch_alter_table('briefing_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefing_preferences_created_at'), ['created_at'], unique=False)

    op.create_table('contact_aliases',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('normalised_alias', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_aliases_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_aliases')),
    sa.UniqueConstraint('normalised_alias', name='uq_contact_aliases_normalised_alias')
    )
    with op.batch_alter_table('contact_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_aliases_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_aliases_created_at'), ['created_at'], unique=False)

    op.create_table('document_records',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('absolute_path', sa.String(length=700), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_ok', sa.Boolean(), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['document_sources.id'], name=op.f('fk_document_records_source_id_document_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_records')),
    sa.UniqueConstraint('source_id', 'relative_path', name='uq_document_records_source_path')
    )
    with op.batch_alter_table('document_records', schema=None) as batch_op:
        batch_op.create_index('ix_document_records_content_hash', ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_records_filename'), ['filename'], unique=False)
        batch_op.create_index('ix_document_records_kind', ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_records_source_id'), ['source_id'], unique=False)

    op.create_table('notification_delivery_attempts',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=60), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_delivery_attempts_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_delivery_attempts'))
    )
    with op.batch_alter_table('notification_delivery_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_delivery_attempts_notification_id'), ['notification_id'], unique=False)

    op.create_table('outfit_history',
    sa.Column('outfit_id', sa.String(length=36), nullable=False),
    sa.Column('worn_on', sa.Date(), nullable=False),
    sa.Column('occasion', sa.String(length=60), nullable=True),
    sa.Column('weather_summary', sa.String(length=200), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('fk_outfit_history_outfit_id_outfits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outfit_history'))
    )
    with op.batch_alter_table('outfit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfit_history_outfit_id'), ['outfit_id'], unique=False)
        batch_op.create_index('ix_outfit_history_worn_on', ['worn_on'], unique=False)

    op.create_table('outfit_items',
    sa.Column('outfit_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True, comment='top, bottom, outer, shoes, ...'),
    sa.ForeignKeyConstraint(['item_id'], ['wardrobe_items.id'], name=op.f('fk_outfit_items_item_id_wardrobe_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('fk_outfit_items_outfit_id_outfits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outfit_id', 'item_id', name=op.f('pk_outfit_items'))
    )
    op.create_table('script_runs',
    sa.Column('script_id', sa.String(length=36), nullable=True),
    sa.Column('script_name', sa.String(length=80), nullable=False),
    sa.Column('arguments_json', sa.Text(), nullable=False),
    sa.Column('resolved_argv_json', sa.Text(), nullable=True, comment='Exact argv array executed. Never a shell string.'),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('stdout_tail', sa.Text(), nullable=True),
    sa.Column('stderr_tail', sa.Text(), nullable=True),
    sa.Column('log_path', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['registered_scripts.id'], name=op.f('fk_script_runs_script_id_registered_scripts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_runs'))
    )
    with op.batch_alter_table('script_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_runs_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_script_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_script_runs_script_id'), ['script_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_script_runs_script_name'), ['script_name'], unique=False)
        batch_op.create_index('ix_script_runs_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('social_post_history',
    sa.Column('outfit_id', sa.String(length=36), nullable=True),
    sa.Column('posted_on', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('fk_social_post_history_outfit_id_outfits'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_post_history')),
    sa.UniqueConstraint('outfit_id', 'posted_on', 'platform', name='uq_social_post_history_entry')
    )
    with op.batch_alter_table('social_post_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_post_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_post_history_outfit_id'), ['outfit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_post_history_posted_on'), ['posted_on'], unique=False)

    op.create_table('tasks',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True, comment='JSON array of tag strings'),
    sa.Column('recurrence_id', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recurrence_id'], ['task_recurrences.id'], name=op.f('fk_tasks_recurrence_id_task_recurrences'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('idempotency_key', name='uq_tasks_idempotency_key')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index('ix_tasks_status_due_at', ['status', 'due_at'], unique=False)

    op.create_table('user_preferences',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner_profile.id'], name=op.f('fk_user_preferences_owner_id_owner_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('owner_id', 'key', name='uq_user_preferences_owner_id_key')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_created_at'), ['created_at'], unique=False)

    op.create_table('wardrobe_availability_events',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['wardrobe_items.id'], name=op.f('fk_wardrobe_availability_events_item_id_wardrobe_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wardrobe_availability_events'))
    )
    with op.batch_alter_table('wardrobe_availability_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wardrobe_availability_events_item_id'), ['item_id'], unique=False)

    op.create_table('wardrobe_images',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.String(length=400), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=400), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('dominant_colors', sa.Text(), nullable=True, comment='JSON array of hex strings'),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['wardrobe_items.id'], name=op.f('fk_wardrobe_images_item_id_wardrobe_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wardrobe_images'))
    )
    with op.batch_alter_table('wardrobe_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wardrobe_images_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_wardrobe_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wardrobe_images_item_id'), ['item_id'], unique=False)

    op.create_table('reminders',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('trigger_at', sa.DateTime(), nullable=False),
    sa.Column('original_trigger_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('recurrence_id', sa.String(length=36), nullable=True),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('snooze_count', sa.Integer(), nullable=False),
    sa.Column('misfire_grace_seconds', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recurrence_id'], ['task_recurrences.id'], name=op.f('fk_reminders_recurrence_id_task_recurrences'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_reminders_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders')),
    sa.UniqueConstraint('idempotency_key', name='uq_reminders_idempotency_key')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_reminders_status_trigger_at', ['status', 'trigger_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_trigger_at'), ['trigger_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_trigger_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_task_id'))
        batch_op.drop_index('ix_reminders_status_trigger_at')
        batch_op.drop_index(batch_op.f('ix_reminders_job_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_created_at'))

    op.drop_table('reminders')
    with op.batch_alter_table('wardrobe_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wardrobe_images_item_id'))
        batch_op.drop_index(batch_op.f('ix_wardrobe_images_created_at'))
        batch_op.drop_index(batch_op.f('ix_wardrobe_images_content_hash'))

    op.drop_table('wardrobe_images')
    with op.batch_alter_table('wardrobe_availability_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wardrobe_availability_events_item_id'))

    op.drop_table('wardrobe_availability_events')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_created_at'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_status_due_at')
        batch_op.drop_index(batch_op.f('ix_tasks_due_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))

    op.drop_table('tasks')
    with op.batch_alter_table('social_post_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_post_history_posted_on'))
        batch_op.drop_index(batch_op.f('ix_social_post_history_outfit_id'))
        batch_op.drop_index(batch_op.f('ix_social_post_history_created_at'))

    op.drop_table('social_post_history')
    with op.batch_alter_table('script_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_script_runs_status_created_at')
        batch_op.drop_index(batch_op.f('ix_script_runs_script_name'))
        batch_op.drop_index(batch_op.f('ix_script_runs_script_id'))
        batch_op.drop_index(batch_op.f('ix_script_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_script_runs_approval_id'))

    op.drop_table('script_runs')
    op.drop_table('outfit_items')
    with op.batch_alter_table('outfit_history', schema=None) as batch_op:
        batch_op.drop_index('ix_outfit_history_worn_on')
        batch_op.drop_index(batch_op.f('ix_outfit_history_outfit_id'))
        batch_op.drop_index(batch_op.f('ix_outfit_history_created_at'))

    op.drop_table('outfit_history')
    with op.batch_alter_table('notification_delivery_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_delivery_attempts_notification_id'))

    op.drop_table('notification_delivery_attempts')
    with op.batch_alter_table('document_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_records_source_id'))
        batch_op.drop_index('ix_document_records_kind')
        batch_op.drop_index(batch_op.f('ix_document_records_filename'))
        batch_op.drop_index(batch_op.f('ix_document_records_created_at'))
        batch_op.drop_index('ix_document_records_content_hash')

    op.drop_table('document_records')
    with op.batch_alter_table('contact_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_aliases_created_at'))
        batch_op.drop_index(batch_op.f('ix_contact_aliases_contact_id'))

    op.drop_table('contact_aliases')
    with op.batch_alter_table('briefing_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefing_preferences_created_at'))

    op.drop_table('briefing_preferences')
    with op.batch_alter_table('background_task_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_task_events_task_id'))

    op.drop_table('background_task_events')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_status_expires_at')
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_created_at'))

    op.drop_table('approvals')
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.drop_index('ix_wardrobe_items_primary_color')
        batch_op.drop_index(batch_op.f('ix_wardrobe_items_laundry_status'))
        batch_op.drop_index(batch_op.f('ix_wardrobe_items_last_worn_on'))
        batch_op.drop_index(batch_op.f('ix_wardrobe_items_created_at'))
        batch_op.drop_index('ix_wardrobe_items_category_archived')
        batch_op.drop_index(batch_op.f('ix_wardrobe_items_category'))

    op.drop_table('wardrobe_items')
    with op.batch_alter_table('task_recurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_recurrences_created_at'))

    op.drop_table('task_recurrences')
    with op.batch_alter_table('service_heartbeats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_heartbeats_created_at'))

    op.drop_table('service_heartbeats')
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_created_at'))

    op.drop_table('scheduled_jobs')
    with op.batch_alter_table('registered_scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_scripts_created_at'))

    op.drop_table('registered_scripts')
    with op.batch_alter_table('pending_reachy_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_reachy_notifications_created_at'))
        batch_op.drop_index('ix_pending_reachy_notifications_ack')

    op.drop_table('pending_reachy_notifications')
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_actions_status_expires_at')
        batch_op.drop_index(batch_op.f('ix_pending_actions_status'))
        batch_op.drop_index(batch_op.f('ix_pending_actions_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_pending_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_pending_actions_background_task_id'))
        batch_op.drop_index(batch_op.f('ix_pending_actions_action_type'))

    op.drop_table('pending_actions')
    with op.batch_alter_table('owner_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_profile_created_at'))

    op.drop_table('owner_profile')
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfits_occasion'))
        batch_op.drop_index(batch_op.f('ix_outfits_last_worn_on'))
        batch_op.drop_index(batch_op.f('ix_outfits_created_at'))

    op.drop_table('outfits')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_dedup_key'))
        batch_op.drop_index('ix_notifications_created_at_severity')
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('integration_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_health_created_at'))

    op.drop_table('integration_health')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_keys_expires_at')
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_created_at'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('document_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sources_created_at'))

    op.drop_table('document_sources')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_relationship_tag'))
        batch_op.drop_index(batch_op.f('ix_contacts_primary_email'))
        batch_op.drop_index('ix_contacts_normalised_name')
        batch_op.drop_index(batch_op.f('ix_contacts_external_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_created_at'))

    op.drop_table('contacts')
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_task_type'))
        batch_op.drop_index('ix_background_tasks_status_available_at')
        batch_op.drop_index(batch_op.f('ix_background_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_lease_owner'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_available_at'))

    op.drop_table('background_tasks')
    with op.batch_alter_table('alert_deduplications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_deduplications_created_at'))
        batch_op.drop_index(batch_op.f('ix_alert_deduplications_alert_kind'))

    op.drop_table('alert_deduplications')
    with op.batch_alter_table('action_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_audit_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_action_audit_log_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_action_audit_log_approval_id'))
        batch_op.drop_index(batch_op.f('ix_action_audit_log_action_type'))

    op.drop_table('action_audit_log')
    # ### end Alembic commands ###
